import '../../models/technician.dart';

class MockTechnicianData {
  static List<Technician> generate() {
    return const [
      Technician(
        id: 't-001',
        name: 'Kwame Boateng',
        specialty: 'Network & Production Systems',
        activeTickets: 8,
        resolvedToday: 4,
        resolvedThisWeek: 23,
        avgResolutionHours: 3.4,
        slaComplianceRate: 0.96,
        customerSatisfaction: 4.7,
        online: true,
        avatarInitials: 'KB',
      ),
      Technician(
        id: 't-002',
        name: 'Yaa Mensah',
        specialty: 'Hardware & Software',
        activeTickets: 6,
        resolvedToday: 3,
        resolvedThisWeek: 19,
        avgResolutionHours: 4.1,
        slaComplianceRate: 0.93,
        customerSatisfaction: 4.5,
        online: true,
        avatarInitials: 'YM',
      ),
      Technician(
        id: 't-003',
        name: 'Kojo Owusu',
        specialty: 'Application Support',
        activeTickets: 11,
        resolvedToday: 2,
        resolvedThisWeek: 16,
        avgResolutionHours: 5.6,
        slaComplianceRate: 0.87,
        customerSatisfaction: 4.3,
        online: false,
        avatarInitials: 'KO',
      ),
      Technician(
        id: 't-004',
        name: 'Abena Asante',
        specialty: 'Identity & Access',
        activeTickets: 4,
        resolvedToday: 5,
        resolvedThisWeek: 27,
        avgResolutionHours: 2.8,
        slaComplianceRate: 0.98,
        customerSatisfaction: 4.8,
        online: true,
        avatarInitials: 'AA',
      ),
      Technician(
        id: 't-005',
        name: 'Nana Adjei',
        specialty: 'Field Support — Tarkwa',
        activeTickets: 7,
        resolvedToday: 3,
        resolvedThisWeek: 18,
        avgResolutionHours: 4.5,
        slaComplianceRate: 0.91,
        customerSatisfaction: 4.4,
        online: true,
        avatarInitials: 'NA',
      ),
      Technician(
        id: 't-006',
        name: 'Akua Pokuaa',
        specialty: 'Field Support — Damang',
        activeTickets: 5,
        resolvedToday: 2,
        resolvedThisWeek: 14,
        avgResolutionHours: 3.9,
        slaComplianceRate: 0.94,
        customerSatisfaction: 4.6,
        online: false,
        avatarInitials: 'AP',
      ),
    ];
  }
}
