import '../../models/asset.dart';

class MockAssetData {
  static List<Asset> generate() {
    final now = DateTime.now();
    DateTime ago(int days) => now.subtract(Duration(days: days));

    return [
      Asset(
        id: 'a-001',
        tag: 'GHA-LT-1042',
        name: 'Akosua Mensah – Laptop',
        model: 'Latitude 7440',
        manufacturer: 'Dell',
        serialNumber: 'DL7440-CN09182M',
        category: AssetCategory.laptop,
        status: AssetStatus.inUse,
        currentUser: 'Akosua Mensah',
        department: 'Operations',
        location: 'Tarkwa Mine',
        purchasedOn: ago(420),
        warrantyUntil: now.add(const Duration(days: 645)),
        cost: 14800,
        assignmentHistory: [
          AssetAssignment(
            userName: 'Akosua Mensah',
            department: 'Operations',
            assignedOn: ago(420),
          ),
        ],
      ),
      Asset(
        id: 'a-002',
        tag: 'GHA-LT-0987',
        name: 'Kofi Asare – Laptop',
        model: 'ThinkPad T14 Gen 3',
        manufacturer: 'Lenovo',
        serialNumber: 'LV-T14-PG88122',
        category: AssetCategory.laptop,
        status: AssetStatus.inUse,
        currentUser: 'Kofi Asare',
        department: 'Plant Maintenance',
        location: 'Tarkwa Mine',
        purchasedOn: ago(280),
        warrantyUntil: now.add(const Duration(days: 815)),
        cost: 13900,
        assignmentHistory: [
          AssetAssignment(
            userName: 'Kofi Asare',
            department: 'Plant Maintenance',
            assignedOn: ago(280),
          ),
        ],
      ),
      Asset(
        id: 'a-003',
        tag: 'GHA-DT-0321',
        name: 'Finance Workstation 03',
        model: 'OptiPlex 7000',
        manufacturer: 'Dell',
        serialNumber: 'DL-OP7000-FN03',
        category: AssetCategory.desktop,
        status: AssetStatus.inUse,
        currentUser: 'Ama Boateng',
        department: 'Finance',
        location: 'Accra HQ',
        purchasedOn: ago(610),
        warrantyUntil: now.add(const Duration(days: 480)),
        cost: 9800,
        assignmentHistory: [
          AssetAssignment(
            userName: 'Kojo Sarpong',
            department: 'Finance',
            assignedOn: ago(610),
            returnedOn: ago(180),
          ),
          AssetAssignment(
            userName: 'Ama Boateng',
            department: 'Finance',
            assignedOn: ago(180),
          ),
        ],
      ),
      Asset(
        id: 'a-004',
        tag: 'GHA-SRV-0011',
        name: 'CIL Plant SCADA Server',
        model: 'PowerEdge R750',
        manufacturer: 'Dell',
        serialNumber: 'DL-PE750-SCADA',
        category: AssetCategory.server,
        status: AssetStatus.inUse,
        currentUser: 'IT Operations',
        department: 'IT Operations',
        location: 'Tarkwa Mine',
        purchasedOn: ago(720),
        warrantyUntil: now.add(const Duration(days: 360)),
        cost: 78000,
        assignmentHistory: [
          AssetAssignment(
            userName: 'IT Operations',
            department: 'IT Operations',
            assignedOn: ago(720),
          ),
        ],
      ),
      Asset(
        id: 'a-005',
        tag: 'GHA-NET-0042',
        name: 'Damang Site Switch',
        model: 'Catalyst 9300',
        manufacturer: 'Cisco',
        serialNumber: 'CSC-9300-DMG42',
        category: AssetCategory.network,
        status: AssetStatus.maintenance,
        currentUser: 'IT Operations',
        department: 'IT Operations',
        location: 'Damang Mine',
        purchasedOn: ago(950),
        warrantyUntil: ago(50),
        cost: 32000,
        assignmentHistory: [
          AssetAssignment(
            userName: 'IT Operations',
            department: 'IT Operations',
            assignedOn: ago(950),
          ),
        ],
      ),
      Asset(
        id: 'a-006',
        tag: 'GHA-PR-0017',
        name: 'Finance Floor Printer',
        model: 'LaserJet Pro M404',
        manufacturer: 'HP',
        serialNumber: 'HP-M404-FN17',
        category: AssetCategory.printer,
        status: AssetStatus.inUse,
        currentUser: 'Finance Department',
        department: 'Finance',
        location: 'Accra HQ',
        purchasedOn: ago(560),
        warrantyUntil: now.add(const Duration(days: 175)),
        cost: 3200,
        assignmentHistory: [
          AssetAssignment(
            userName: 'Finance Department',
            department: 'Finance',
            assignedOn: ago(560),
          ),
        ],
      ),
      Asset(
        id: 'a-007',
        tag: 'GHA-LT-1118',
        name: 'IT Spare – Laptop',
        model: 'Latitude 5440',
        manufacturer: 'Dell',
        serialNumber: 'DL5440-SP1118',
        category: AssetCategory.laptop,
        status: AssetStatus.inStock,
        currentUser: '—',
        department: 'IT Operations',
        location: 'Accra HQ',
        purchasedOn: ago(45),
        warrantyUntil: now.add(const Duration(days: 1050)),
        cost: 12400,
        assignmentHistory: const [],
      ),
      Asset(
        id: 'a-008',
        tag: 'GHA-MOB-0233',
        name: 'Field Phone — Geology',
        model: 'Galaxy XCover 6 Pro',
        manufacturer: 'Samsung',
        serialNumber: 'SM-XC6P-GE233',
        category: AssetCategory.mobile,
        status: AssetStatus.inUse,
        currentUser: 'Yaw Darko',
        department: 'Geology',
        location: 'Damang Mine',
        purchasedOn: ago(140),
        warrantyUntil: now.add(const Duration(days: 590)),
        cost: 4200,
        assignmentHistory: [
          AssetAssignment(
            userName: 'Yaw Darko',
            department: 'Geology',
            assignedOn: ago(140),
          ),
        ],
      ),
      Asset(
        id: 'a-009',
        tag: 'GHA-LT-0712',
        name: 'Old HR Laptop (retired)',
        model: 'Latitude 5420',
        manufacturer: 'Dell',
        serialNumber: 'DL5420-HR0712',
        category: AssetCategory.laptop,
        status: AssetStatus.retired,
        currentUser: '—',
        department: 'Human Resources',
        location: 'Accra HQ',
        purchasedOn: ago(1380),
        warrantyUntil: ago(280),
        cost: 11900,
        assignmentHistory: [
          AssetAssignment(
            userName: 'Adwoa Frimpong',
            department: 'Human Resources',
            assignedOn: ago(1380),
            returnedOn: ago(80),
          ),
        ],
      ),
      Asset(
        id: 'a-010',
        tag: 'GHA-SRV-0008',
        name: 'Accra HQ File Server',
        model: 'PowerEdge R650',
        manufacturer: 'Dell',
        serialNumber: 'DL-PE650-FS08',
        category: AssetCategory.server,
        status: AssetStatus.inUse,
        currentUser: 'IT Operations',
        department: 'IT Operations',
        location: 'Accra HQ',
        purchasedOn: ago(640),
        warrantyUntil: now.add(const Duration(days: 440)),
        cost: 64500,
        assignmentHistory: [
          AssetAssignment(
            userName: 'IT Operations',
            department: 'IT Operations',
            assignedOn: ago(640),
          ),
        ],
      ),
      Asset(
        id: 'a-011',
        tag: 'GHA-NET-0050',
        name: 'Tarkwa Wi-Fi AP — Canteen',
        model: 'Aironet 1815',
        manufacturer: 'Cisco',
        serialNumber: 'CSC-1815-CT50',
        category: AssetCategory.network,
        status: AssetStatus.inUse,
        currentUser: 'IT Operations',
        department: 'IT Operations',
        location: 'Tarkwa Mine',
        purchasedOn: ago(380),
        warrantyUntil: now.add(const Duration(days: 720)),
        cost: 1850,
        assignmentHistory: [
          AssetAssignment(
            userName: 'IT Operations',
            department: 'IT Operations',
            assignedOn: ago(380),
          ),
        ],
      ),
      Asset(
        id: 'a-012',
        tag: 'GHA-MON-0091',
        name: 'Procurement 27" Monitor',
        model: 'UltraSharp U2722D',
        manufacturer: 'Dell',
        serialNumber: 'DL-U2722D-PR91',
        category: AssetCategory.peripheral,
        status: AssetStatus.inUse,
        currentUser: 'Kwesi Antwi',
        department: 'Procurement',
        location: 'Accra HQ',
        purchasedOn: ago(220),
        warrantyUntil: now.add(const Duration(days: 510)),
        cost: 2800,
        assignmentHistory: [
          AssetAssignment(
            userName: 'Kwesi Antwi',
            department: 'Procurement',
            assignedOn: ago(220),
          ),
        ],
      ),
    ];
  }
}
